from ww.corpus.index import update_records

updates = {
  49378: {
    'tier': 'teaching',
    'summary': '5-day EMA post-GLB exit rule; 4wk>10wk>30wk up-trend confirmation; GLBs rocketing in 2026',
    'indicators': ['GLB', '5-day EMA', '4wk avg', '10wk avg', '30wk avg', 'GMI'],
    'tickers': ['QQQ', 'INTC', 'AMD', 'CHAT'],
    'ingested': True,
    'summary_page': 'wiki/sources/2026-05-10-bog-post-day-22-of-qqq-short-term-up-trend-qqq-10-wk-avg-now-closes-week-above-30-wk-avg-gmigreen-glb-breakou.md',
  },
  44450: {
    'tier': 'teaching',
    'summary': 'QQQ sitting on its green line top and 30-week average; Stage 4 warning signs; rotation to utilities/energy',
    'indicators': ['GLB', '30wk avg', '4wk avg', '10wk avg', 'GMI', 'stochastic 10.4'],
    'tickers': ['QQQ'],
    'ingested': True,
    'summary_page': 'wiki/sources/2026-02-16-blog-day-8-of-qqq-short-term-down-trend-utilities-had-most-aths-13-see-list-followed-by-oilgas-10-rotation-aw.md',
  },
  45895: {
    'tier': 'teaching',
    'summary': 'GMI=0 and Red; 30-week average curving down = Weinstein Stage 4 onset; T2108 at 23%; oversold bounce possible',
    'indicators': ['GMI', '30wk avg', '10wk avg', 'T2108', 'stage analysis'],
    'tickers': ['QQQ'],
    'ingested': True,
    'summary_page': 'wiki/sources/2026-03-15-blog-post-day-27-of-qqq-short-term-down-trend-gmi-0-and-red-more-new-us-52-week-lows-than-highs-this-weekly-c.md',
  },
  29854: {
    'tier': 'teaching',
    'summary': 'Blue dot of happiness scan: TC2000 formula for stochastic 10.1 cross above 20; full scan criteria with Bollinger Band 15.2, monthly ATH, volume',
    'indicators': ['stochastic 10.1', 'Bollinger Band 15.2', 'blue dot'],
    'tickers': [],
    'ingested': True,
    'summary_page': 'wiki/sources/2025-05-22-blog-post-day-20-of-qqq-short-term-up-trend-thank-you-for-attending-my-presentation-to-the-boston-ibd-meetup.md',
  },
  30297: {
    'tier': 'teaching',
    'summary': 'Blue dot re-entry after emotional exit; stop losses as sine qua non; 5-day EMA tracking post-GLB; chicken trader discipline',
    'indicators': ['blue dot', 'stop loss', 'GMI', '5-day EMA'],
    'tickers': ['QQQ', 'SPY'],
    'ingested': True,
    'summary_page': 'wiki/sources/2025-08-10-blog-post-day-73-of-qqq-short-term-up-trend-shaken-out-but-back-in-blue-dot-of-happiness-signal-held-see-dail.md',
  },
  29583: {
    'tier': 'teaching',
    'summary': 'T2108 at 7% = bottoms-tend-to-occur zone; 10wk/30wk cross down for first time since 2023; claim that market timing IS possible',
    'indicators': ['T2108', '10wk avg', '30wk avg', 'GMI', 'SQQQ'],
    'tickers': ['QQQ', 'SQQQ', 'TWM'],
    'ingested': True,
    'summary_page': 'wiki/sources/2025-04-06-blog-post-day-29-of-qqq-short-term-down-trend-t2108-declines-to-7-where-bottoms-tend-to-occur-we-can-time-the.md',
  },
  32016: {
    'tier': 'teaching',
    'summary': '4wk bounce-off-weekly-average entry; 4wk>10wk>30wk alignment in up-trend; stop below weekly bounce low; Halloween seasonality note',
    'indicators': ['4wk avg', '10wk avg', '30wk avg', 'stage analysis'],
    'tickers': ['SPY', 'QQQ'],
    'ingested': True,
    'summary_page': 'wiki/sources/2025-10-23-blog-post-day-43-of-qqq-short-term-up-trend-come-back-at-halloween-barring-bad-inflation-news-friday-my-indic.md',
  },
  30023: {
    'tier': 'teaching',
    'summary': 'GLB applied to mutual funds; 10wk/30wk crossover for pension; Guppy weekly RWB on QQQ; limit losses as prerequisite to long-run success',
    'indicators': ['GLB', '10wk avg', '30wk avg', 'Guppy', 'RWB', 'GMI'],
    'tickers': ['FCNKX', 'QQQ', 'SPY'],
    'ingested': True,
    'summary_page': 'wiki/sources/2025-06-29-blog-post-day-44-of-qqq-short-term-up-trend-ta-works-also-for-mutual-funds-see-glb-last-week-in-fidelity-cont.md',
  },
  28268: {
    'tier': 'teaching',
    'summary': 'x8/x21/30-day EMA alignment as new bounce entry setup; TC2000 scan criteria: ATH within 5 weeks, up 50%+ YoY, bouncing off x8',
    'indicators': ['8-day EMA', '21-day EMA', '30-day avg', 'GLB', 'T2108'],
    'tickers': ['COST', 'ANF', 'NVDA', 'CVLT'],
    'ingested': True,
    'summary_page': 'wiki/sources/2024-06-16-blog-post-day-29-of-qqq-short-term-up-trend-introducing-the-x8-x21-30-day-set-up-examplescost-anf-nvda-cvlt.md',
  },
  27099: {
    'tier': 'teaching',
    'summary': 'Canonical 2023 GLB re-statement with PGR worked example; buy-high-sell-higher philosophy; sell immediately on close below green line',
    'indicators': ['GLB', 'IBD MS rating'],
    'tickers': ['PGR', 'CMG', 'MSFT', 'DUOL', 'WING'],
    'ingested': True,
    'summary_page': 'wiki/sources/2023-11-26-very-important-blog-post-explaining-glbs-day-15-of-qqq-short-term-up-trend-123-us-new-highs-and-2-lows-43-at.md',
  },
  25278: {
    'tier': 'trade_example',
    'summary': 'CRDO GLB failure due to after-hours earnings shock; hard stops cannot protect against gap-downs; position-sizing lesson',
    'indicators': ['GLB', 'stop loss'],
    'tickers': ['CRDO'],
    'ingested': True,
    'summary_page': 'wiki/sources/2023-02-15-blog-post-day-24-of-qqq-short-term-up-trend-when-technical-analysis-fails-crdo-my-confession.md',
  },
  18808: {
    'tier': 'teaching',
    'summary': 'Bounce-off-support entry strategy: green dot stochastic signal; stop placed below recent low; application to COVID-era growth stocks',
    'indicators': ['green dot', 'stochastic', '30-day avg', 'GLB'],
    'tickers': ['DDOG', 'ETSY', 'NET', 'BAND', 'SEDG'],
    'ingested': True,
    'summary_page': 'wiki/sources/2020-07-19-blog-post-my-bounce-off-of-support-strategy-some-possible-examples-ddog-etsy-net-band-plmr-domo-cien-ping-adb.md',
  },
  19216: {
    'tier': 'teaching',
    'summary': 'Monitoring GLBs during corrections to find emerging leaders; weekly chart rule for holding winners; PINS, PTON, ZM, CRWD examples; T2108 at 23%',
    'indicators': ['GLB', '10wk avg', '4wk avg', 'T2108', 'GMI'],
    'tickers': ['PINS', 'PTON', 'ZM', 'FVRR', 'TSLA', 'CRWD'],
    'ingested': True,
    'summary_page': 'wiki/sources/2020-09-27-this-week-will-determine-if-tech-down-trend-will-continue-monitoring-glbs-to-find-leaders-during-a-correction.md',
  },
  14225: {
    'tier': 'teaching',
    'summary': 'GLB applied to IPOs; IIPR and FB worked examples; green dot as re-entry after missed GLB; QQQ short-term trend duration statistics table',
    'indicators': ['GLB', 'green dot', 'GMI'],
    'tickers': ['IIPR', 'FB'],
    'ingested': True,
    'summary_page': 'wiki/sources/2019-04-07-trading-ipos-with-a-glb-and-a-green-dot-signal-iipr-qqq-short-term-up-trend-is-in-61st-day.md',
  },
  7584: {
    'tier': 'teaching',
    'summary': 'DW as GLB worked example; GLB tracker table concept; weekly scan for 52wk high + above-average volume; ATH-only philosophy explained for students',
    'indicators': ['GLB', 'GLB tracker', 'volume scan'],
    'tickers': ['DW', 'MELI', 'SHOP'],
    'ingested': True,
    'summary_page': 'wiki/sources/2016-09-05-dw-a-successful-green-line-break-out-updated-glb-tracker-table-all-gmi-components-positive.md',
  },
}

update_records('raw/posts.jsonl', updates)
print('Done - 15 posts updated')
